import type { ReadingOrder } from "@/types/domain";

export const MOCK_READING_ORDERS: ReadingOrder[] = [
  {
    id: "ro-marvel-saga",
    slug: "jonathan-hickmans-marvel-saga",
    creatorId: "user-marcus",
    title: "Jonathan Hickman's Marvel Saga",
    summary:
      "The full Hickman throughline from Fantastic Four's Solar System-in-a-box to the end of Secret Wars, in publication-friendly reading order.",
    description:
      "Hickman's Marvel work forms one continuous argument about entropy, legacy, and what the Marvel Universe owes its future. This order threads Fantastic Four and FF into S.H.I.E.L.D. and Secret Warriors before merging into the two Avengers titles and their satellite minis, ending at Infinity and Secret Wars. Read this if you want the authorial through-line rather than strict issue chronology.",
    coverImageUrl: "",
    publishers: ["marvel"],
    categories: ["creator", "era", "universe"],
    visibility: "public",
    saveCount: 3120,
    viewCount: 48211,
    estimatedBookCount: 24,
    createdAt: "2023-03-01T10:00:00.000Z",
    updatedAt: "2026-06-15T16:20:00.000Z",
    entries: [
      {
        id: "entry-marvel-saga-1",
        readingOrderId: "ro-marvel-saga",
        position: 1,
        entryType: "collected-edition",
        title: "Fantastic Four by Jonathan Hickman Omnibus",
        subtitle: "Volume 1",
        issueRange: "FF (2009) #570–578",
        notes:
          "Start here even if you've never read Fantastic Four. Hickman re-establishes the cast fast.",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-2",
        readingOrderId: "ro-marvel-saga",
        position: 2,
        entryType: "collected-edition",
        title: "S.H.I.E.L.D. by Hickman & Weaver",
        issueRange: "S.H.I.E.L.D. (2010) #1–6",
        notes: "Runs parallel in-universe; introduces the Brotherhood of the Shield mythology.",
        isOptional: true,
      },
      {
        id: "entry-marvel-saga-3",
        readingOrderId: "ro-marvel-saga",
        position: 3,
        entryType: "collected-edition",
        title: "Fantastic Four by Jonathan Hickman Omnibus",
        subtitle: "Volume 2",
        issueRange: "FF (2009) #579–588",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-4",
        readingOrderId: "ro-marvel-saga",
        position: 4,
        entryType: "collected-edition",
        title: "Avengers by Jonathan Hickman Omnibus",
        subtitle: "Volume 1",
        issueRange: "Avengers (2013) #1–11",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-5",
        readingOrderId: "ro-marvel-saga",
        position: 5,
        entryType: "collected-edition",
        title: "New Avengers by Jonathan Hickman Omnibus",
        subtitle: "Volume 1",
        issueRange: "New Avengers (2013) #1–12",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-6",
        readingOrderId: "ro-marvel-saga",
        position: 6,
        entryType: "collected-edition",
        title: "Infinity",
        issueRange: "Infinity (2013) #1–6",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-7",
        readingOrderId: "ro-marvel-saga",
        position: 7,
        entryType: "reading-note",
        title: "Time Runs Out",
        notes:
          "The Avengers and New Avengers Omnibus lines converge here; read both titles issue-by-issue in publication order through to Secret Wars.",
        isOptional: false,
      },
      {
        id: "entry-marvel-saga-8",
        readingOrderId: "ro-marvel-saga",
        position: 8,
        entryType: "collected-edition",
        title: "Secret Wars",
        issueRange: "Secret Wars (2015) #1–9",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-krakoa-xmen",
    slug: "krakoa-era-x-men",
    creatorId: "user-marcus",
    title: "Krakoa Era X-Men",
    summary:
      "House of X and Powers of X through the founding line's first year, mapped across the flagship titles that actually matter to the metaplot.",
    description:
      "The Krakoa era launched with a dense two-title event and fanned out into a dozen ongoing books. This order gets you through the mandatory HoXPoX setup, then follows the three titles doing the heaviest metaplot lifting before the era's first major status-quo shift. It intentionally skips books that are good but non-essential to the central thread; see the notes on optional entries for detours worth taking later.",
    coverImageUrl: "",
    publishers: ["marvel"],
    categories: ["era", "team", "universe"],
    visibility: "public",
    saveCount: 2870,
    viewCount: 61304,
    estimatedBookCount: 14,
    createdAt: "2023-09-10T08:30:00.000Z",
    updatedAt: "2026-07-20T09:05:00.000Z",
    entries: [
      {
        id: "entry-krakoa-1",
        readingOrderId: "ro-krakoa-xmen",
        position: 1,
        entryType: "collected-edition",
        title: "House of X / Powers of X",
        issueRange: "HoX/PoX (2019) #1–6",
        notes: "Mandatory. Read the two series interleaved in release order, not back to back.",
        isOptional: false,
      },
      {
        id: "entry-krakoa-2",
        readingOrderId: "ro-krakoa-xmen",
        position: 2,
        entryType: "collected-edition",
        title: "X-Men by Jonathan Hickman",
        subtitle: "Volume 1",
        issueRange: "X-Men (2019) #1–6",
        isOptional: false,
      },
      {
        id: "entry-krakoa-3",
        readingOrderId: "ro-krakoa-xmen",
        position: 3,
        entryType: "collected-edition",
        title: "Marauders",
        subtitle: "Volume 1",
        issueRange: "Marauders (2019) #1–6",
        isOptional: false,
      },
      {
        id: "entry-krakoa-4",
        readingOrderId: "ro-krakoa-xmen",
        position: 4,
        entryType: "collected-edition",
        title: "X-Force",
        subtitle: "Volume 1",
        issueRange: "X-Force (2019) #1–6",
        isOptional: false,
      },
      {
        id: "entry-krakoa-5",
        readingOrderId: "ro-krakoa-xmen",
        position: 5,
        entryType: "collected-edition",
        title: "Excalibur",
        subtitle: "Volume 1",
        issueRange: "Excalibur (2019) #1–6",
        notes: "Optional but recommended if you want the Otherworld subplot before it pays off later.",
        isOptional: true,
      },
      {
        id: "entry-krakoa-6",
        readingOrderId: "ro-krakoa-xmen",
        position: 6,
        entryType: "story-arc",
        title: "X of Swords",
        issueRange: "X of Swords crossover, all titles",
        notes: "The first line-wide crossover. Requires every flagship title current through this point.",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-batman-morrison",
    slug: "batman-by-grant-morrison",
    creatorId: "user-priya",
    title: "Batman by Grant Morrison",
    summary:
      "Every issue of Morrison's seven-year Batman run, from 'Batman and Son' through Batman Incorporated, in the order that actually makes the ending land.",
    description:
      "Morrison's run rewards patience and punishes skipping around. This order keeps the Robin/Damian arc, the Club of Villains, R.I.P., Final Crisis's Batman fallout, Return of Bruce Wayne, and both volumes of Batman Incorporated in their intended sequence, with crossover chapters folded in where Morrison actually wrote them rather than where DC originally solicited them.",
    coverImageUrl: "",
    publishers: ["dc"],
    categories: ["creator", "character"],
    visibility: "public",
    saveCount: 2456,
    viewCount: 39877,
    estimatedBookCount: 11,
    createdAt: "2022-11-05T13:00:00.000Z",
    updatedAt: "2026-05-02T11:40:00.000Z",
    entries: [
      {
        id: "entry-batman-morrison-1",
        readingOrderId: "ro-batman-morrison",
        position: 1,
        entryType: "collected-edition",
        title: "Batman and Son",
        issueRange: "Batman (1940) #655–658",
        isOptional: false,
      },
      {
        id: "entry-batman-morrison-2",
        readingOrderId: "ro-batman-morrison",
        position: 2,
        entryType: "collected-edition",
        title: "The Black Glove",
        issueRange: "Batman (1940) #667–669, 672–675",
        isOptional: false,
      },
      {
        id: "entry-batman-morrison-3",
        readingOrderId: "ro-batman-morrison",
        position: 3,
        entryType: "collected-edition",
        title: "Batman R.I.P.",
        issueRange: "Batman (1940) #676–681",
        isOptional: false,
      },
      {
        id: "entry-batman-morrison-4",
        readingOrderId: "ro-batman-morrison",
        position: 4,
        entryType: "reading-note",
        title: "Final Crisis detour",
        notes:
          "Read Final Crisis #6–7 here for the direct follow-up to R.I.P. before continuing into Batman and Robin.",
        isOptional: true,
      },
      {
        id: "entry-batman-morrison-5",
        readingOrderId: "ro-batman-morrison",
        position: 5,
        entryType: "collected-edition",
        title: "Batman and Robin",
        subtitle: "Volume 1: Batman Reborn",
        issueRange: "Batman and Robin (2009) #1–6",
        isOptional: false,
      },
      {
        id: "entry-batman-morrison-6",
        readingOrderId: "ro-batman-morrison",
        position: 6,
        entryType: "collected-edition",
        title: "Return of Bruce Wayne",
        issueRange: "The Return of Bruce Wayne (2010) #1–6",
        isOptional: false,
      },
      {
        id: "entry-batman-morrison-7",
        readingOrderId: "ro-batman-morrison",
        position: 7,
        entryType: "collected-edition",
        title: "Batman Incorporated",
        subtitle: "Volume 1",
        issueRange: "Batman Incorporated (2011) #1–8",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-dc-crisis",
    slug: "dc-crisis-reading-path",
    creatorId: "user-priya",
    title: "DC Crisis Reading Path",
    summary:
      "Crisis on Infinite Earths through Final Crisis: how DC's multiverse got destroyed, rebuilt, and destroyed again, in the order the ideas actually build.",
    description:
      "Each Crisis event redefines the last one's consequences, which makes cold chronological order actively confusing for new readers. This path front-loads the original 1985 Crisis, then Zero Hour and Infinite Crisis back to back since Infinite Crisis is a direct response to the first, closing with 52 as connective tissue into Final Crisis.",
    coverImageUrl: "",
    publishers: ["dc"],
    categories: ["event", "universe"],
    visibility: "public",
    saveCount: 1988,
    viewCount: 33210,
    estimatedBookCount: 9,
    createdAt: "2023-01-18T15:20:00.000Z",
    updatedAt: "2026-04-11T10:10:00.000Z",
    entries: [
      {
        id: "entry-dc-crisis-1",
        readingOrderId: "ro-dc-crisis",
        position: 1,
        entryType: "collected-edition",
        title: "Crisis on Infinite Earths",
        issueRange: "Crisis on Infinite Earths (1985) #1–12",
        isOptional: false,
      },
      {
        id: "entry-dc-crisis-2",
        readingOrderId: "ro-dc-crisis",
        position: 2,
        entryType: "collected-edition",
        title: "Zero Hour: Crisis in Time",
        issueRange: "Zero Hour (1994) #4–0",
        isOptional: false,
      },
      {
        id: "entry-dc-crisis-3",
        readingOrderId: "ro-dc-crisis",
        position: 3,
        entryType: "collected-edition",
        title: "Infinite Crisis",
        issueRange: "Infinite Crisis (2005) #1–7",
        isOptional: false,
      },
      {
        id: "entry-dc-crisis-4",
        readingOrderId: "ro-dc-crisis",
        position: 4,
        entryType: "collected-edition",
        title: "52",
        subtitle: "Omnibus",
        notes: "Weekly series bridging Infinite Crisis and Final Crisis; long but worth it for continuity payoff.",
        isOptional: false,
      },
      {
        id: "entry-dc-crisis-5",
        readingOrderId: "ro-dc-crisis",
        position: 5,
        entryType: "collected-edition",
        title: "Final Crisis",
        issueRange: "Final Crisis (2008) #1–7",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-daredevil",
    slug: "daredevil-by-bendis-and-brubaker",
    creatorId: "user-sam",
    title: "Daredevil by Bendis and Brubaker",
    summary:
      "The full 'Matt Murdock's life falls apart' saga, from Bendis's unmasking arc through Brubaker's prison-and-redemption run, read as one story.",
    description:
      "Bendis and Brubaker wrote Daredevil as a continuous tragedy across roughly ten years of the character's life. This order treats their combined runs as a single reading experience: Bendis's identity-reveal fallout through the Purple/Owl war, straight into Brubaker taking Matt to prison and back out again.",
    coverImageUrl: "",
    publishers: ["marvel"],
    categories: ["creator", "character"],
    visibility: "public",
    saveCount: 1542,
    viewCount: 27650,
    estimatedBookCount: 8,
    createdAt: "2024-06-02T12:00:00.000Z",
    updatedAt: "2026-07-01T14:50:00.000Z",
    entries: [
      {
        id: "entry-daredevil-1",
        readingOrderId: "ro-daredevil",
        position: 1,
        entryType: "collected-edition",
        title: "Daredevil by Brian Michael Bendis Omnibus",
        subtitle: "Volume 1",
        issueRange: "Daredevil (1998) #16–35",
        isOptional: false,
      },
      {
        id: "entry-daredevil-2",
        readingOrderId: "ro-daredevil",
        position: 2,
        entryType: "collected-edition",
        title: "Daredevil by Brian Michael Bendis Omnibus",
        subtitle: "Volume 2",
        issueRange: "Daredevil (1998) #36–50, #56–81",
        isOptional: false,
      },
      {
        id: "entry-daredevil-3",
        readingOrderId: "ro-daredevil",
        position: 3,
        entryType: "collected-edition",
        title: "Daredevil by Ed Brubaker Omnibus",
        subtitle: "Volume 1",
        issueRange: "Daredevil (1998) #82–93, (2006) #500",
        isOptional: false,
      },
      {
        id: "entry-daredevil-4",
        readingOrderId: "ro-daredevil",
        position: 4,
        entryType: "collected-edition",
        title: "Daredevil by Ed Brubaker Omnibus",
        subtitle: "Volume 2",
        issueRange: "Daredevil (2006) #101–119",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-hellboy-bprd",
    slug: "hellboy-and-the-bprd",
    creatorId: "user-diego",
    title: "Hellboy and the B.P.R.D.",
    summary:
      "Mignola's Hellboy interleaved with B.P.R.D. so the two series' shared timeline unfolds the way it was plotted, not the way it was published.",
    description:
      "Hellboy and B.P.R.D. run in parallel, and Mignola plotted them to inform each other. This order interleaves the two series chronologically rather than by publication imprint, so Hellboy's descent toward Hellboy in Hell lines up with the Bureau's slow-burn apocalypse in B.P.R.D.",
    coverImageUrl: "",
    publishers: ["dark-horse"],
    categories: ["character", "universe"],
    visibility: "public",
    saveCount: 1204,
    viewCount: 21044,
    estimatedBookCount: 16,
    createdAt: "2024-02-14T09:45:00.000Z",
    updatedAt: "2026-03-19T17:30:00.000Z",
    entries: [
      {
        id: "entry-hellboy-1",
        readingOrderId: "ro-hellboy-bprd",
        position: 1,
        entryType: "collected-edition",
        title: "Hellboy: Seed of Destruction",
        isOptional: false,
      },
      {
        id: "entry-hellboy-2",
        readingOrderId: "ro-hellboy-bprd",
        position: 2,
        entryType: "collected-edition",
        title: "Hellboy: Wake the Devil",
        isOptional: false,
      },
      {
        id: "entry-hellboy-3",
        readingOrderId: "ro-hellboy-bprd",
        position: 3,
        entryType: "collected-edition",
        title: "B.P.R.D.: Hollow Earth and Other Stories",
        notes: "First B.P.R.D. material; introduces the Bureau cast that carries the rest of the order.",
        isOptional: false,
      },
      {
        id: "entry-hellboy-4",
        readingOrderId: "ro-hellboy-bprd",
        position: 4,
        entryType: "collected-edition",
        title: "Hellboy: The Chained Coffin and Others",
        isOptional: false,
      },
      {
        id: "entry-hellboy-5",
        readingOrderId: "ro-hellboy-bprd",
        position: 5,
        entryType: "collected-edition",
        title: "B.P.R.D.: The Soul of Venice and Other Stories",
        isOptional: true,
      },
      {
        id: "entry-hellboy-6",
        readingOrderId: "ro-hellboy-bprd",
        position: 6,
        entryType: "collected-edition",
        title: "Hellboy in Hell",
        subtitle: "Library Edition",
        notes: "The endpoint of Hellboy's own arc; read after at least Plague of Frogs-era B.P.R.D. for full weight.",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-berserk-deluxe",
    slug: "berserk-deluxe-edition-reading-order",
    creatorId: "user-yuki",
    title: "Berserk Deluxe Edition Reading Order",
    summary:
      "Kentaro Miura's Berserk mapped onto the oversized Dark Horse Deluxe hardcovers, three tankōbon per volume, for collectors buying the deluxe line.",
    description:
      "The Deluxe hardcovers repackage three original volumes each in a larger trim with cleaner reproduction. This reading order exists mainly to answer 'which Deluxe volume do I buy next,' since the numbering doesn't map 1:1 to the original tankōbon anyone quoting chapter numbers is usually citing.",
    coverImageUrl: "",
    publishers: ["dark-horse"],
    categories: ["manga-series"],
    visibility: "public",
    saveCount: 987,
    viewCount: 18932,
    estimatedBookCount: 13,
    createdAt: "2024-01-05T07:20:00.000Z",
    updatedAt: "2026-07-25T19:10:00.000Z",
    entries: [
      {
        id: "entry-berserk-1",
        readingOrderId: "ro-berserk-deluxe",
        position: 1,
        entryType: "collected-edition",
        title: "Berserk Deluxe Edition",
        subtitle: "Volume 1",
        notes: "Collects the original tankōbon volumes 1–3: the Black Swordsman and Golden Age arcs begin.",
        isOptional: false,
      },
      {
        id: "entry-berserk-2",
        readingOrderId: "ro-berserk-deluxe",
        position: 2,
        entryType: "collected-edition",
        title: "Berserk Deluxe Edition",
        subtitle: "Volume 2",
        isOptional: false,
      },
      {
        id: "entry-berserk-3",
        readingOrderId: "ro-berserk-deluxe",
        position: 3,
        entryType: "collected-edition",
        title: "Berserk Deluxe Edition",
        subtitle: "Volume 3",
        notes: "The Golden Age arc concludes here. Emotionally, pace yourself.",
        isOptional: false,
      },
      {
        id: "entry-berserk-4",
        readingOrderId: "ro-berserk-deluxe",
        position: 4,
        entryType: "collected-edition",
        title: "Berserk Deluxe Edition",
        subtitle: "Volume 4",
        isOptional: false,
      },
    ],
  },
  {
    id: "ro-invincible-compendium",
    slug: "invincible-compendium-reading-order",
    creatorId: "user-diego",
    title: "Invincible Compendium Reading Order",
    summary:
      "Kirkman and Walker's full Invincible run mapped onto the three Compendium paperbacks, for readers who want the whole series in as few spines as possible.",
    description:
      "The Compendium editions collect roughly 47–48 issues each in a single phonebook-format paperback. This is less a 'reading order' than a shelf plan for the person who wants the entire original series without hunting down individual trades, kept private for now while I confirm issue ranges against my own copies.",
    coverImageUrl: "",
    publishers: ["image"],
    categories: ["character", "custom"],
    visibility: "private",
    saveCount: 512,
    viewCount: 9820,
    estimatedBookCount: 3,
    createdAt: "2025-01-11T21:00:00.000Z",
    updatedAt: "2026-02-08T08:00:00.000Z",
    entries: [
      {
        id: "entry-invincible-1",
        readingOrderId: "ro-invincible-compendium",
        position: 1,
        entryType: "collected-edition",
        title: "Invincible Compendium",
        subtitle: "One",
        issueRange: "Invincible (2003) #1–47",
        isOptional: false,
      },
      {
        id: "entry-invincible-2",
        readingOrderId: "ro-invincible-compendium",
        position: 2,
        entryType: "collected-edition",
        title: "Invincible Compendium",
        subtitle: "Two",
        issueRange: "Invincible (2003) #48–96",
        isOptional: false,
      },
      {
        id: "entry-invincible-3",
        readingOrderId: "ro-invincible-compendium",
        position: 3,
        entryType: "collected-edition",
        title: "Invincible Compendium",
        subtitle: "Three",
        issueRange: "Invincible (2003) #97–144",
        isOptional: false,
      },
    ],
  },
];
