import type { CollectedEditionReview } from "@/types/domain";

export const MOCK_REVIEWS: CollectedEditionReview[] = [
  {
    id: "review-ff-hickman-omnibus-1",
    authorId: "user-marcus",
    editionTitle: "Fantastic Four by Jonathan Hickman Omnibus, Vol. 1",
    publisher: "marvel",
    coverImageUrl: "",
    overallRating: 4.5,
    reviewText:
      "The reproduction on the early FF (2009) pages is noticeably cleaner than the original trades, and the binding holds flat even past the halfway point, which matters on a book this thick. The chronology map in the endpapers is genuinely useful for cross-referencing S.H.I.E.L.D. and Secret Warriors without leaving your seat. My only complaint is a couple of noticeably soft-focus pages carried over from the original scans rather than rescanned for this printing.",
    bindingRating: 4,
    paperQualityRating: 4,
    mappingRating: 5,
    extrasRating: 3,
    createdAt: "2025-03-02T10:00:00.000Z",
    updatedAt: "2025-03-02T10:00:00.000Z",
  },
  {
    id: "review-avengers-hickman-omnibus-1",
    authorId: "user-marcus",
    editionTitle: "Avengers by Jonathan Hickman Omnibus, Vol. 1",
    publisher: "marvel",
    coverImageUrl: "",
    overallRating: 4,
    reviewText:
      "Solid omnibus, though it arrives right as the story's just getting its footing, so it reads a little inconclusive on its own. The included reading-order map for the Avengers/New Avengers split is the best I've seen in a Marvel omnibus and single-handedly justifies the purchase if you're doing a full Hickman readthrough.",
    bindingRating: 4,
    paperQualityRating: 4,
    mappingRating: 5,
    extrasRating: 2,
    createdAt: "2025-08-19T09:30:00.000Z",
    updatedAt: "2025-08-19T09:30:00.000Z",
  },
  {
    id: "review-batman-rip-omnibus-1",
    authorId: "user-priya",
    editionTitle: "Batman by Grant Morrison Omnibus, Vol. 2",
    publisher: "dc",
    coverImageUrl: "",
    overallRating: 4.5,
    reviewText:
      "Covers R.I.P. through Battle for the Cowl in one spine, which is exactly the awkward stretch that's hardest to find in print otherwise. Paper stock is a step up from DC's older omnibus runs — noticeably less show-through on the darker Tony Daniel pages. Extras are thin: just a handful of variant covers and no annotations, which is a missed opportunity given how much this run rewards a guided re-read.",
    bindingRating: 5,
    paperQualityRating: 4,
    extrasRating: 2,
    createdAt: "2025-01-27T14:15:00.000Z",
    updatedAt: "2025-01-27T14:15:00.000Z",
  },
  {
    id: "review-absolute-crisis-1",
    authorId: "user-priya",
    editionTitle: "Absolute Crisis on Infinite Earths",
    publisher: "dc",
    coverImageUrl: "",
    overallRating: 5,
    reviewText:
      "This is the format Crisis always deserved. The oversized trim actually lets you follow the double-page splashes without a magnifying glass, and the slipcase construction feels sturdy rather than decorative. George Pérez's linework was made for this size. Genuinely one of the best physical objects in my collection, DC omnibus or otherwise.",
    bindingRating: 5,
    paperQualityRating: 5,
    extrasRating: 4,
    createdAt: "2025-11-04T18:45:00.000Z",
    updatedAt: "2025-11-04T18:45:00.000Z",
  },
  {
    id: "review-hellboy-library-1",
    authorId: "user-diego",
    editionTitle: "Hellboy Library Edition, Vol. 1: Seed of Destruction and Wake the Devil",
    publisher: "dark-horse",
    coverImageUrl: "",
    overallRating: 4.5,
    reviewText:
      "Dark Horse's Library Editions remain the gold standard for how to reprint Mignola. Matte paper stock suits the inks far better than the glossier original trade printings did, and the binding is Smyth-sewn, so it opens flat for the full-page compositions without any spine stress. The only reason this isn't a perfect score is a thin selection of extras compared to what later Hellboy in Hell volumes included.",
    bindingRating: 5,
    paperQualityRating: 5,
    extrasRating: 3,
    createdAt: "2025-05-13T12:20:00.000Z",
    updatedAt: "2025-05-13T12:20:00.000Z",
  },
  {
    id: "review-berserk-deluxe-1-1",
    authorId: "user-yuki",
    editionTitle: "Berserk Deluxe Edition, Vol. 1",
    publisher: "dark-horse",
    coverImageUrl: "",
    overallRating: 5,
    reviewText:
      "Worth the upgrade from the standard tankōbon purely on paper quality alone — the larger trim size does real justice to Miura's linework, especially the double-page spreads in the Golden Age arc that felt cramped in the original volumes. Hardcover binding is sturdy enough to survive being read more than once, which given the page count and my track record with paperbacks is not nothing.",
    bindingRating: 5,
    paperQualityRating: 5,
    extrasRating: 3,
    createdAt: "2025-02-08T08:10:00.000Z",
    updatedAt: "2025-02-08T08:10:00.000Z",
  },
  {
    id: "review-vagabond-vizbig-1",
    authorId: "user-yuki",
    editionTitle: "Vagabond VIZBIG Edition, Vol. 1",
    publisher: "viz",
    coverImageUrl: "",
    overallRating: 4,
    reviewText:
      "VIZBIG collects three volumes per book at a reasonable price, and the larger format does wonders for Inoue's brushwork-heavy pages. Paper is slightly thinner than I'd like given how much ink coverage some of these pages have, and there's minor bleed-through visible against bright panels. Still the best way to own this series in English.",
    bindingRating: 4,
    paperQualityRating: 3,
    extrasRating: 2,
    createdAt: "2025-09-21T15:50:00.000Z",
    updatedAt: "2025-09-21T15:50:00.000Z",
  },
  {
    id: "review-daredevil-brubaker-omnibus-1",
    authorId: "user-sam",
    editionTitle: "Daredevil by Ed Brubaker Omnibus, Vol. 1",
    publisher: "marvel",
    coverImageUrl: "",
    overallRating: 4,
    reviewText:
      "Picks up cleanly from the Bendis Omnibus and the tonal shift into the prison arc reads even better collected than it did in singles. Binding is standard Marvel omnibus quality, meaning fine but not exceptional, and it doesn't sit fully flat on early pages. No complaints about the printing itself — Lark and Rivera's art holds up well at this size.",
    bindingRating: 3,
    paperQualityRating: 4,
    extrasRating: 3,
    createdAt: "2025-06-30T20:05:00.000Z",
    updatedAt: "2025-06-30T20:05:00.000Z",
  },
];
