import type { UserProfile } from "@/types/domain";

export const MOCK_USERS: UserProfile[] = [
  {
    id: "user-marcus",
    username: "marcus.reads",
    displayName: "Marcus Chen",
    bio: "Tracking every Hickman thread since Fantastic Four #570. Krakoa completionist. I annotate my own reading orders way too much.",
    avatarUrl: "",
    location: "Portland, OR",
    favoritePublishers: ["marvel", "image"],
    followerCount: 1284,
    followingCount: 96,
    publishedReadingOrderCount: 2,
    reviewCount: 2,
    createdAt: "2023-02-11T09:00:00.000Z",
  },
  {
    id: "user-priya",
    username: "priya.omnibus",
    displayName: "Priya Nair",
    bio: "DC Omnibus collector and long-form continuity untangler. Grant Morrison's Batman rewired my brain in 2007 and I never recovered.",
    avatarUrl: "",
    location: "Chicago, IL",
    favoritePublishers: ["dc"],
    followerCount: 2031,
    followingCount: 143,
    publishedReadingOrderCount: 2,
    reviewCount: 2,
    createdAt: "2022-08-04T14:30:00.000Z",
  },
  {
    id: "user-diego",
    username: "diego.bprd",
    displayName: "Diego Ortiz",
    bio: "Dark Horse and creator-owned collector. B.P.R.D. is the best-plotted ongoing horror epic in the medium and I will die on that hill.",
    avatarUrl: "",
    location: "Austin, TX",
    favoritePublishers: ["dark-horse", "image"],
    followerCount: 742,
    followingCount: 211,
    publishedReadingOrderCount: 2,
    reviewCount: 1,
    createdAt: "2024-01-22T18:15:00.000Z",
  },
  {
    id: "user-yuki",
    username: "yuki.tankobon",
    displayName: "Yuki Tanaka",
    bio: "Deluxe-edition manga collector. I compare paper stock the way other people compare wine. Currently rebuilding my shelf around hardcovers.",
    avatarUrl: "",
    location: "Seattle, WA",
    favoritePublishers: ["viz", "kodansha"],
    followerCount: 956,
    followingCount: 58,
    publishedReadingOrderCount: 1,
    reviewCount: 2,
    createdAt: "2023-11-30T11:45:00.000Z",
  },
  {
    id: "user-sam",
    username: "sam.longbox",
    displayName: "Sam Okafor",
    bio: "Street-level Marvel reader. Daredevil, Hawkeye, and whatever Zdarsky is doing this week. Building reading orders so newcomers don't bounce off Bendis's run order.",
    avatarUrl: "",
    location: "Brooklyn, NY",
    favoritePublishers: ["marvel"],
    followerCount: 518,
    followingCount: 302,
    publishedReadingOrderCount: 1,
    reviewCount: 1,
    createdAt: "2024-05-09T20:00:00.000Z",
  },
];
